CREATE DATABASE rasr;
USE rasr;
CREATE TABLE abc
(
  ab_ib INT UNSIGNED,
  ab_name VARCHAR (56)
);
SELECT * FROM abc;

INSERT INTO abc VALUES (112, "DATA");
INSERT INTO abc VALUES (115, "ANALYSIS");

TRUNCATE TABLE abc;
DROP TABLE abc;

